all:
  vars:
    ansible_user: pbech
    ansible_become_method: sudo
    
  children:
    k3s_master:
      hosts:
        harbour-lighthouse:
          ansible_host: 192.168.164.2
          ansible_become: true
    k3s_workers:
      hosts:
        harbour-dock-1:
          ansible_host: 192.168.164.3
          ansible_become: true
        harbour-dock-2:
          ansible_host: 192.168.164.4
          ansible_become: true
  
