apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
  template:
    metadata:
      labels:
        app: metallb
    spec:
      containers:
        - name: controller
          image: metallb/controller:v0.13.13
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metallb-speaker
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app: metallb-speaker
  template:
    metadata:
      labels:
        app: metallb-speaker
    spec:
      hostNetwork: true
      containers:
        - name: speaker
          image: metallb/speaker:v0.13.13
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: harbour-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.164.10-192.168.164.19
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: harbour-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - harbour-pool
