- name: Install NFS packages
  apt:
    name: "{{ nfs_packages }}"
    state: present
    update_cache: true

- name: Ensure export directories exist
  file:
    path: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: "0777"
  loop: "{{ nfs_exports }}"

- name: Configure /etc/exports from template
#  lineinfile:
#    path: /etc/exports
#    line: "{{ item.path }} {{ item.network }}({{ item.options }})"
#    create: yes
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
#  loop: "{{ nfs_exports }}"
  notify: Restart NFS

- name: Ensure exports are active
  command: exportfs -ra
  notify: Restart NFS

- name: Ensure NFS server is running
  service:
    name: nfs-kernel-server
    state: started
    enabled: true

- name: Ensure Pi-hole NFS directory exists
  file:
    path: /srv/k8s-storage/pihole
    state: directory
    owner: nobody
    group: nogroup
    mode: "0777"